apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  template:
    spec:
      containers:
      - args:  
        - gateway
        - azure
      - env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: secretkey
        - name: AZURE_STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: azurestorageaccount
        - name: AZURE_STORAGE_KEY
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: azurestoragekey
#        volumeMounts:
#          $patch: delete
#      volumes:
#        $patch: delete
